<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.co.kc.im</groupId>
        <artifactId>im-chat</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>im-plugin</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>im-cache</module>
        <module>im-identity</module>
        <module>im-excel</module>
        <module>im-metrics</module>
        <module>im-lock</module>
        <module>im-datasource</module>
        <module>im-session</module>
        <module>im-web</module>
        <module>im-dubbo</module>
        <module>im-bolt</module>
        <module>im-mq-kafka</module>
        <module>im-gossip</module>
        <module>im-nacos</module>
    </modules>
</project>
