server:
  port: 18080

spring:
  application:
    name: im-http-gateway
  config:
    import:
      - optional:nacos:${spring.application.name}.yml?group=${im.nacos.config.infra-group:INFRA_GROUP}
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
          globalcors:
            cors-configurations:
              '[/**]':
                allowedHeaders: '*'
                allowedMethods: '*'
                allowedOrigins: '*'
          routes:
            - id: im-account
              uri: lb://im-account
              predicates:
                - Path=/account/**
            - id: im-message
              uri: lb://im-message
              predicates:
                - Path=/message/**
            - id: im-social
              uri: lb://im-social
              predicates:
                - Path=/social/**
