server:
  port: 19011

spring:
  application:
    name: im-ws-gateway
  config:
    import:
      - optional:nacos:${spring.application.name}.yml?group=${im.nacos.config.infra-group:INFRA_GROUP}
  cloud:
    nacos:
      discovery:
        port: ${im.gateway.ws.port}

management:
  server:
    port: 19011
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: never

im:
  bolt:
    client:
      enabled: true
    server:
      enabled: true
      port: 18012
  gateway:
    ws:
      port: 18011
      bind-host: ${IM_GATEWAY_BIND_HOST:0.0.0.0}
      host: ${IM_GATEWAY_HOST:127.0.0.1}
      path: /ws
      max-frame-payload-length: 65536
      idle:
        reader-idle-seconds: 60
      bolt:
        host: ${im.gateway.ws.host}
      broker:
        bolt:
          load-balance: HASH
          timeout-millis: 3000
