spring:
  application:
    name: im-ws-gateway
  main:
    web-application-type: none
  config:
    import:
      - optional:nacos:${spring.application.name}.yml?group=${im.nacos.config.infra-group:INFRA_GROUP}
  cloud:
    nacos:
      discovery:
        port: ${im.gateway.ws.port}

management:
  endpoints:
    jmx:
      exposure:
        include: health,metrics

im:
  bolt:
    client:
      enabled: true
    server:
      enabled: true
      port: 12201
  gateway:
    ws:
      port: 19090
      host: ${IM_GATEWAY_HOST:127.0.0.1}
      path: /ws
      max-frame-payload-length: 65536
      idle:
        reader-idle-seconds: 60
      register:
        enabled: true
      bolt:
        host: ${im.gateway.ws.host}
      broker:
        bolt:
          load-balance: HASH
          timeout-millis: 3000
