server:
  port: 18032
  servlet:
    context-path: /message

management:
  server:
    port: 19032
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: never

spring:
  application:
    name: im-message
  config:
    import:
      - optional:nacos:${spring.application.name}.yml?group=${im.nacos.config.service-group:SERVICE_GROUP}
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
      ssl:
        enabled: false
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: ${spring.data.redis.password}
          subscriptionsPerConnection: 5
          clientName: null
          address: "${im.redis.redisson.address:redis://127.0.0.1:6379}"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          database: 0
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.client.codec.ByteArrayCodec> {}
        transportMode: "NIO"
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: false
    #热部署文件，页面不产生缓存，及时更新
    cache: false
    servlet:
      content-type: text/html
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  autoconfigure:
    exclude:
      - org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration
      - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration
  mvc:
    favicon:
      enabled: false
    pathmatch:
      matching-strategy: ant_path_matcher

im:
  datasource:
    sharding:
      enabled: true
      config-location: classpath:im-sharding.yml
  identity:
    snowflake:
      mode: STATIC
      data-center-id: 1
      machine-id: 1
  bolt:
    client:
      enabled: true
  message:
    broker:
      bolt:
        timeout-millis: 3000

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /api/doc.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.co.kc.imchat

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: false
  setting:
    language: zh_cn

# MyBatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 将数据库字段的下划线命名转换为驼峰命名
  mapper-locations: classpath:mapper/*.xml # MyBatis映射文件所在的位置，这里是使用XML的配置方式时需要配置的部分

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    localCacheScope: STATEMENT
    cacheEnabled: false
