server:
  port: 8887
  servlet:
    context-path: /social

springdoc:
  swagger-ui:
    path: /api/doc.html
  api-docs:
    path: /v3/api-docs

im:
  identity:
    snowflake:
      mode: STATIC
      data-center-id: 1
      machine-id: 1

spring:
  application:
    name: im-social
  config:
    import:
      - optional:nacos:${spring.application.name}.yml?group=${im.nacos.config.service-group:SERVICE_GROUP}
  datasource:
    url: jdbc:mysql://localhost:3306/im_chat_social?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
